### ISSUE TITLE
无法添加邀请码？

### ISSUE THREAD

**Issue by z886** [likeyun/WeChat-Group-HuoMa#15]
用的最新版本，非常感谢大佬提供的源码，今天安装后初步试用了下，发现无法添加邀请码，其它功能暂时没发现问题。
![123](https://user-images.githubusercontent.com/2437974/104028137-5470f300-5203-11eb-82dc-7196e368c879.png)

**Comment by iiidcc** [comment]
> 用的最新版本，非常感谢大佬提供的源码，今天安装后初步试用了下，发现无法添加邀请码，其他功能暂时没发现问题。
> ![123](https://user-images.githubusercontent.com/2437974/104028137-5470f300-5203-11eb-82dc-7196e368c879.png)

更换PHP版本5.6~7.0    还是不行的话就重新搭建，实测是可以添加邀请码的。

**Comment by likeyun** [comment]
可以去设置qun_huoma_yqm这个表，除id外，其他字段设置允许为空

**Comment by z886** [comment]
好的，谢谢！
