### ISSUE TITLE
上传二维码并分享时，url不是自己的域名

### ISSUE THREAD

**Issue by carlsue** [likeyun/WeChat-Group-HuoMa#5]
![image](https://user-images.githubusercontent.com/17507066/86751177-1129a200-c071-11ea-9e21-f5e27583ae77.png)

**Comment by likeyun** [comment]
那肯定是你服务器配置出了问题

**Comment by carlsue** [comment]
> 那肯定是你服务器配置出了问题

好的，那我再仔细检查下

**Comment by carlsue** [comment]
测试了确实是自己的问题，他读取的是主域名，额外域名不行的。

现在发现另外一个小bug，我站点是https的，上传的图片他自动添加的是http。导致客户访问时页面显示不安全，http内容图片可能不能显示
