### ISSUE TITLE
有没有多用户版本？每个人注册都可以用。

### ISSUE THREAD

**Issue by iseeyou** [likeyun/WeChat-Group-HuoMa#7]
现在用户名密码在json里面

**Comment by likeyun** [comment]
目前github是我的测试代码，我忘了把正式版本代码放上去了，测试代码的json会暴露你的用户账号和密码，晚点换上，先别安装

**Comment by likeyun** [comment]
> 现在用户名密码在json里面

目前github是我的测试代码，我忘了把正式版本代码放上去了，测试代码的json会暴露你的用户账号和密码，晚点换上，先别安装

**Comment by likeyun** [comment]
> 现在用户名密码在json里面

已经上传正式版，多用户版本还在开发中~
